services:
  - type: web
    name: n8n-automation
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        sync: false
